### ISSUE TITLE
Penicillin removing effects that shouldn't be removed

### ISSUE THREAD

**Issue by IAA-ShRaPNeL** [jakimfett/Minechem#631] opened 2015-02-12 18:38 UTC
Penicillin currently removes some effects that shouldn't be able to be removed by normal means, such as Extra- Util flight and Soulfray from Blood magic. 

Forge Version: forge-1.7.10-10.13.2.1277-universal

Minechem Version: MINECHEM-1.7.10-5.0.5.358

**Comment by hilburn** [comment] 2015-02-13 01:58
Ex-U flight is not actually an issue, and Soul Fray is bugged to allow removal through milk and other potion removal methods

**Comment by jakimfett** [comment] 2015-02-13 02:12
Should be fixed by https://github.com/jakimfett/Minechem/pull/632

@IAA-ShRaPNeL could I get you to test this with the latest build from the [Minechem Jenkins](http://jenkins.jakimfett.com/view/ForgeModding/job/Minechem%201.7%20v5/)?

**Comment by hilburn** [comment] 2015-02-13 09:26
Oh @jakimfett - can't test it, the BM potion is bugged and is actually removable

**Comment by IAA-ShRaPNeL** [comment] 2015-02-13 22:34
Hmm. Milk wasn't removing it.

**Comment by hilburn** [comment] 2015-02-13 23:13
try a milk bottle

**Comment by IAA-ShRaPNeL** [comment] 2015-02-14 15:07
I should clarify. Milk Bucket doesn't. Milk Bottle may. I'l report that to MFR.

**Comment by hilburn** [comment] 2015-02-14 15:09
don't report it to MFR, it's not a bug

**Closed** 2015-02-14 16:20 UTC
Labels: confirmed bug, fixed in dev
